### ISSUE TITLE
Files are write protected

### ISSUE THREAD

**Issue by pieterlange** [michthom/AlwaysAppendSearchDomains#3]
The proper way to do this now is:
`sudo launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist`
`sudo defaults write /Library/Preferences/com.apple.mDNSResponder.plist AlwaysAppendSearchDomains -bool YES`
`sudo launchctl load /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist`

**Comment by michthom** [comment]
Thanks Pieter. Committed to the readme, and the older scripts demoted.

**Comment by qrpike** [comment]
I get the following:
```
000:~ qrpike$ sudo launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
/System/Library/LaunchDaemons/com.apple.mDNSResponder.plist: Operation not permitted while System Integrity Protection is engaged
```

**Comment by michthom** [comment]
Hi Quinton - the clue is in the error message:
"Operation not permitted while System Integrity Protection is engaged"
Did you skip the step to disable SIP?

**Comment by michthom** [comment]
Shut down fully
Start up while holding down Command-R
Choose Utilities > Terminal from the menu bar
Type the commands:
```
csrutil disable
reboot
```
