### ISSUE TITLE
launchctl unload doesn't work on Sierra

### ISSUE THREAD

**Issue by rfay** [michthom/AlwaysAppendSearchDomains#5]
On MacOS Sierra the specified 
`sudo launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist` 

fails with `/System/Library/LaunchDaemons/com.apple.mDNSResponder.plist: Operation not permitted while System Integrity Protection is engaged`

It's not recommended to turn SIP off....

**Comment by michthom** [comment]
Thanks Randy, I've updated the Readme to reflect that (but explain how to do it if people want to).
